---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentry-kafka
  namespace: "default"
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: sentry
automountServiceAccountToken: true
