---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sentry-rabbitmq-endpoint-reader
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: sentry
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
