---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sentry-rabbitmq-endpoint-reader
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: sentry
subjects:
  - kind: ServiceAccount
    name: sentry-rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sentry-rabbitmq-endpoint-reader
