---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentry-rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: sentry
automountServiceAccountToken: true
secrets:
  - name: sentry-rabbitmq
