---
# Source: sentry/templates/hooks/sentry-secret-create.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry-sentry-secret
  labels:
    app: sentry
    chart: "sentry-20.9.3"
    release: "sentry"
    heritage: "Helm"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "3"
type: Opaque
data:
  key: "dm40T0FnTFpWTXBNVWJzVXBWT0w2d1FhT3gxR2R3ODloMmhpTE9ncEkwQWJlUTFGRUM="
