---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-ingest-occurrences
  labels:
    app: sentry
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sentry
      role: ingest-occurrences
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry
        role: ingest-occurrences
    spec:
      affinity:
      containers:
      - name: sentry-ingest-occurrences
        image: "getsentry/sentry:23.10.1"
        imagePullPolicy: IfNotPresent
        command: ["sentry"]
        args:
          - "run"
          - "consumer"
          - "ingest-occurrences"
          - "--consumer-group"
          - "ingest-occurrences"
        env:
        - name: C_FORCE_ROOT
          value: "true"
        - name: SNUBA
          value: http://sentry-snuba:1218
        - name: VROOM
          value: http://sentry-vroom:8085
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentry-sentry-secret
              key: "key"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-postgresql-secret
              key: postgres-password
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: /var/lib/sentry/files
          name: sentry-data
        resources:
            {}
      volumes:
      - name: config
        configMap:
          name: sentry-sentry
      - name: sentry-data
        emptyDir: {}
