---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-web
  labels:
    app: sentry
spec:
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sentry
      role: web
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry
        role: web
    spec:
      affinity:
      containers:
      - name: sentry-web
        image: "getsentry/sentry:23.10.1"
        imagePullPolicy: IfNotPresent
        command: ["sentry", "run", "web"]
        ports:
        - containerPort: 9000
        env:
        - name: SNUBA
          value: http://sentry-snuba:1218
        - name: VROOM
          value: http://sentry-vroom:8085
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentry-sentry-secret
              key: "key"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-postgresql-secret
              key: postgres-password
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: /var/lib/sentry/files
          name: sentry-data
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /_health/
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /_health/
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
            {}
      volumes:
      - name: config
        configMap:
          name: sentry-sentry
      - name: sentry-data
        persistentVolumeClaim:
          claimName: sentry-data
