---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sentry-sentry-secret
spec:
  encryptedData:
    admin_pass: AgAkkpELNgrm/syxoE52DolCfUaQVwWKaU0gsyPfkdz5x3LidlYBILjU2Ccxn1PKTvABFOxjXtGzaAeX3fqMnkcozqNUCR5cIMKJKfxDyKSB3WCOfB0V+fKyEJP8ckeR/PS9Ly7dY/Wp9DN0goTu7HLjWliGXpR8utnz0wtDYFXqJqTEnZrJnNArdi/OX+9xcGqfmcKvvl3+b6npmkxITnPJj/Ze4t88GPQs4lp4zCYF6H3PeFXr0eEXIp0fxFJ9VSTy4+yCnd9daEkg1jRYoMRMWHdKirBe4foz+eAPemJYrL09d8JJyxUcgF9KfP/FQqKCiIQVN0YpMRepDHnP3Xa9WQSZKgF4dZ5bkkjkQ4Pdi66Cw6cGxaGvpKHJpm+/JB4ShUp7wPMIoroQRETJxvl2dYNS9eWQ3OqExIYpxoNEVRex4RrQlfWF/Sdl9vndzpPp71qMJfifVh5dlFeMPXo3wYm4qkMN+ujUZkxdzPDABTjEdsDaivCk18iz2ecGOCwOaiv+Hoy1IfApKCfR4LL0J/u6ybu73PH9b0z73CAOCtTwiGkSeBAMKsOOGBQGXWt4eMqeBIebCnE5EI0PCsTKhl+6GP0FcAhJ736Fu7EmeWvcPGG1Z1C+6uSfWNwtWWsGVJoMZ9Epe2BNQO1UJIyqzV6WZpX6DsqaR3ipB+1zIT8JAAuby6wHCRFmKJAuulKh0WiLSd/Jg54QGuSTDg==
    admin_user: AgAFzgxPFB5mwmdeAqZO4LGTBm3pAQ1SRfX1U3KmKwJAdIkrOprLK67rqFrF203GG3d64oKavX9mvXrNWBkWOxCrOZBatgZ8P83llnwxUJskBSxcL2bdAyPKg3XZy8+97RPvLcbROi68g590WRX4d4TqtKK4wdrxHSIp7P5F24QLQaCUTWWhnjhP0IJbM9dOm+5rmjZnrpUby9Rd+FbKW3YlJPMbDsW3njTxi+DYaib1v81zAVlSlYQMf4bYWQZoXEdWLOfZsNfoQ5p0c8Ns2FzNZJMT7Nli88HVC8WyqOIMdxlkXMFAVuAgoiLI8pltdsfs8/TA4CbpqzImIzPbUKYAXglCrlG178eWFa3+4VURmkfKVjOFslVoA5dWqLLRtUwg2QvdnewRmSn+DlX9JIY6iveFs9jhx7zevB/F8vj5nBGUbCLzJtY88+SeXOPhlSENdHl89nyWtN2PKw+h9pRQaBa2cHvbYVCKOSSvHzHxb/VjNaP+unXLNwECE8/04zmd+123iqLVRXjkhRSKkjSZqafwWwNORML0BIUlBSAKUOlYejwSmRkPXcG8zvdl71RobLljETQpdor0bt9APAedzPNurFNm9pnIwbT+WGT4z5xpTU14y/DF367ithQZ7fF92KFVAskcJQbcraVtsVy/AdmBT0lMKCjMrT7wxOtheTfJxGscpNgXiZ+Isrxq8qXcoklpEKIlxfDkTHx0oce8Rdc=
    key: AgCGi6QGLyPuKqOaYZsGXMIC/YbiUat++lfXDpvd0d/UVblJfvo/PsyH9UUujbG0wSvOvyECFnMpLE213Hsrb8cETQFV8u1+JtQiGBi3EYdSucT3Yu4HncdUEHBk1yF+XskbbyyqwWEFH17L3SJcqR5ZPt95k6iznUG7VyN6fENrWeLPf7pqHfVsjtqZhSSauZb7Cm+qw5e9GLNHFPRLiAyGvdNdoMFnMvm+aqx3fOmtG9saCREGcBKbQ3psmvjcp5m2gwlhIP7hzI3BnWvR7UCZUSajTUDJjluFUVLn9ZL07LRYyj8R34De7N42crYKFeSUCyhUlUW5T0jyel7uFG6yUMkKlqA7xIOYsUejHZ5csEbvZPas0lRztqinUhF4rAB5H/9jrSRwkPOEbe8vUyjwTb4VNtmmIl2L5tXbV8Hh0ctKpH1kgPPjh8jF8mc4R5or8qMT84RKd2hpGApn6jVgW50XFmcCEGgf5YzMTqqcbeKEeLelOOSdlVvMEGHjhyqfnaDR4kpwlHTP6u7+aCh5+J+jVk2y+SGGPM74KePAWnVN4OZssZqnQctrUyGoAbdeTZJL1Td0PfXqfXpIoINHuuVyFRG6aUvcM+5Hv6PgVv8FDs3AChbQ3XU/e6+8oaFB2/k6NG7xcPqkzj8/R6DqfYLvegNlsfuQ1ZOzsGUtuMn41/PeEBzH2yJHEnlWHKRXRZnn/GTKG9LuGYxR2rEEyXL4xY6hvcEOrD+rEgl9Si/r8rjDUsVo07fk7BhsLmgHkA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app: sentry
      name: sentry-sentry-secret
    type: Opaque
