---
# Source: sentry/templates/service-sentry.yaml
apiVersion: v1
kind: Service
metadata:
  name: sentry-web
  annotations:
  labels:
    app: sentry
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: sentry
  selector:
    app: sentry
    role: web
