---
# Source: sentry/templates/hooks/user-create.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sentry-user-create
  labels:
    app: sentry
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: sentry-user-create
      annotations:
      labels:
        app: sentry
    spec:
      restartPolicy: Never
      containers:
      - name: user-create-job
        image: "getsentry/sentry:23.10.1"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        # Create user but do not exit 1 when user already exists (exit code 3 from createuser command)
        # https://docs.sentry.io/server/cli/createuser/
        args:
        - |
          sleep 180;
          sentry createuser \
            --no-input \
            --superuser \
            --email "${ADMIN_USER}" \
            --password "${ADMIN_PASSWORD}" || true; \
          if [ $? -eq 0 ] || [ $? -eq 3 ]; then \
            exit 0; \
          else \
            exit 1; \
          fi
        env:
        - name: SNUBA
          value: http://sentry-snuba:1218
        - name: VROOM
          value: http://sentry-vroom:8085
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentry-sentry-secret
              key: "key"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-postgresql-secret
              key: postgres-password
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-sentry-secret
              key: admin_pass
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: sentry-sentry-secret
              key: admin_user
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        resources:
          limits:
            memory: 2048Mi
          requests:
            cpu: 300m
            memory: 2048Mi
      volumes:
      - name: config
        configMap:
          name: sentry-sentry
