---
# Source: sentry/charts/rabbitmq/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentry-rabbitmq
  namespace: "default"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-11.15.3
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
secrets:
  - name: sentry-rabbitmq
