---
# Source: sentry/charts/zookeeper/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: sentry-zookeeper-clickhouse-headless
  namespace: default
  labels:
    app.kubernetes.io/name: zookeeper-clickhouse
    helm.sh/chart: zookeeper-9.0.0
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-client
      port: 2181
      targetPort: client
    - name: tcp-follower
      port: 2888
      targetPort: follower
    - name: tcp-election
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/name: zookeeper-clickhouse
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/component: zookeeper
