---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-snuba-replacer
  labels:
    app: sentry
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
        app: sentry
        role: snuba-replacer
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry
        role: snuba-replacer
    spec:
      affinity:
      containers:
      - name: sentry-snuba
        image: "getsentry/snuba:23.10.1"
        imagePullPolicy: IfNotPresent
        command:
          - "snuba"
          - "replacer"
          - "--storage"
          - "errors"
          - "--auto-offset-reset"
          - "earliest"
        ports:
        - containerPort: 1218
        env:
        - name: SNUBA_SETTINGS
          value: /etc/snuba/settings.py
        - name: DEFAULT_BROKERS
          value: "sentry-kafka:9092"
        envFrom:
        - secretRef:
            name: sentry-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
        resources:
            {}
      volumes:
      - name: config
        configMap:
          name: sentry-snuba
