---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-snuba-api
  labels:
    app: sentry
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sentry
      role: snuba-api
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry
        role: snuba-api
    spec:
      affinity:
      containers:
      - name: sentry-snuba
        image: "getsentry/snuba:23.10.1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1218
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SNUBA_SETTINGS
          value: /etc/snuba/settings.py
        - name: DEFAULT_BROKERS
          value: "sentry-kafka.$(NAMESPACE).svc.cluster.local:9092"
        envFrom:
        - secretRef:
            name: sentry-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 1218
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 1218
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
            {}
      volumes:
        - name: config
          configMap:
            name: sentry-snuba
