---
apiVersion: v1
kind: Service
metadata:
  name: sentry-snuba
  annotations:
  labels:
    app: sentry
spec:
  type: ClusterIP
  ports:
  - port: 1218
    targetPort: 1218
    protocol: TCP
    name: sentry
  selector:
    app: sentry
    role: snuba-api
