---
apiVersion: batch/v1
kind: Job
metadata:
  name: sentry-snuba-db-init
  labels:
    app: sentry
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: sentry-snuba-db-init
      labels:
        app: sentry
    spec:
      restartPolicy: Never
      containers:
      - name: snuba-init
        image: "getsentry/snuba:23.10.1"
        command: ["/bin/bash", "-c"]
        args:
        - |
          sleep 40;
          snuba bootstrap --no-migrate --kafka --force;
        env:
        - name: LOG_LEVEL
          value: debug
        - name: SNUBA_SETTINGS
          value: /etc/snuba/settings.py
        - name: DEFAULT_BROKERS
          value: "sentry-kafka:9092"
        envFrom:
        - secretRef:
            name: sentry-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            # cpu: 700m
            # memory: 1Gi
            cpu: 500m
            memory: 600Mi
      volumes:
      - name: config
        configMap:
          name: sentry-snuba
