---
apiVersion: v1
kind: Service
metadata:
  name: sentry-sentry-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/name: sentry-postgresql
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/name: sentry-postgresql
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/component: primary
