---
# Source: sentry/charts/redis/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sentry-sentry-redis-headless
  namespace: "default"
  labels:
    app.kubernetes.io/name: sentry-redis
    app.kubernetes.io/instance: sentry
  annotations:
    
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    app.kubernetes.io/name: sentry-redis
    app.kubernetes.io/instance: sentry
