---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: sentry-sentry-redis
  namespace: "default"
  labels:
    app.kubernetes.io/name: sentry-redis
    app.kubernetes.io/instance: sentry
