---
apiVersion: v1
kind: Service
metadata:
  name: sentry-sentry-redis-replicas
  namespace: "default"
  labels:
    app.kubernetes.io/name: sentry-redis
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/component: replica
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
      nodePort: null
  selector:
    app.kubernetes.io/name: sentry-redis
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/component: replica
