---
# Source: sentry/charts/nginx/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sentry-nginx
  namespace: "default"
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-14.2.2
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: ClusterIP
  type: NodePort
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: sentry
