---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentry-nginx
data:
  nginx.conf: |
    # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
    # user              www www;  ## Default: nobody

    worker_processes  auto;
    error_log         "/opt/bitnami/nginx/logs/error.log";
    pid               "/opt/bitnami/nginx/tmp/nginx.pid";

    events {
        worker_connections  1024;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;
      log_format    main '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status  $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log    "/opt/bitnami/nginx/logs/access.log" main;
      add_header    X-Frame-Options SAMEORIGIN;

      client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
      proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
      fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
      scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
      # uwsgi_temp_path

      sendfile           on;
      tcp_nopush         on;
      tcp_nodelay        off;
      gzip               on;
      gzip_http_version  1.0;
      gzip_comp_level    2;
      gzip_proxied       any;
      gzip_types         text/plain text/css application/javascript text/xml application/xml+rss;
      keepalive_timeout  65;
      ssl_protocols      TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
      ssl_ciphers        HIGH:!aNULL:!MD5;
      client_max_body_size 80M;
      server_tokens off;

      absolute_redirect  off;
      port_in_redirect   off;


      upstream relay {
        server sentry-relay:3000;
      }

      upstream sentry {
        server sentry-web:9000;
        # server nginx:80;
      }

      server {
        include  "/opt/bitnami/nginx/conf/bitnami/*.conf";
        listen 8080;

        proxy_redirect off;
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
        proxy_set_header Host $host;

        location /api/store/ {
          proxy_pass http://relay;
        }

        location ~ ^/api/[1-9]\d*/ {
          proxy_pass http://relay;
        }  

        location / {
          proxy_pass http://sentry;
        }

        location /_static/ {
          proxy_pass http://sentry;
          proxy_hide_header Content-Disposition;
        }
      }
    }
