---
# Source: sentry/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry-sentry-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/name: sentry-postgresql
    helm.sh/chart: postgresql-12.5.1
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "cXhlNWhOU09GRQ=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
